[package]
name = "sccp-sol-program"
version = "0.1.0"
edition = "2021"
license = "BSD-4-Clause"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
borsh = { version = "0.10" }
borsh-derive = { version = "0.10" }
solana-program = "1.14.20"
spl-token = { version = "3.5.0", features = ["no-entrypoint"] }
sccp-sol = { path = ".." }

[features]
default = []

[dev-dependencies]
solana-program-test = "1.14.20"
solana-sdk = "1.14.20"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
sccp-sol-verifier-program = { path = "../verifier-program" }
tiny-keccak = { version = "2", features = ["keccak"] }
libsecp256k1 = "0.7"
